load("@io_bazel_rules_go//go:def.bzl", "go_library")

go_library(
    name = "util",
    srcs = [
        "code.go",
        "text.go",
    ],
    importpath = "github.com/crackcomm/llmlsp/llmlsp/util",
    visibility = ["//visibility:public"],
)
